[window]
padding = {x = 10, y = 10}
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.9

[terminal]
shell = "/bin/zsh"

[font]
normal = { family ="JetBrainsMono Nerd Font", style = "Regular" }
bold = { family ="JetBrainsMono Nerd Font", style = "Bold" }
italic = { family ="JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = {family = "JetBrainsMono Nerd Font", style = "BoldItalic"}
size = 15

[colors.primary]
foreground = "#cccccc"
background = "#1e1e1e"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"
