[window]
padding = {x = 10, y = 10}
startup_mode = "Maximized"
dynamic_title = true


[font]
normal = { family ="Mononoki Nerd Font", style = "Regular" }
bold = { family ="Mononoki Nerd Font", style = "Bold" }
italic = { family ="Mononoki Nerd Font", style = "Italic" }
bold_italic = {family = "Mononoki Nerd Font", style = "BoldItalic"}
size = 15





[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
